name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Staging"]
    types: [completed]

jobs:
  deploy-prod:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: docker pull ghcr.io/${{ github.repository }}/serving:production
      - run: docker stop serving-app || true
      - run: docker rm serving-app || true

      - name: Run production
        run: |
          docker run -d --name serving-app -p 8080:8080 \
          ghcr.io/${{ github.repository }}/serving:production